services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: parking_user
      POSTGRES_PASSWORD: parking_pass
      POSTGRES_DB: parking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rtsp:
    image: aler9/rtsp-simple-server
    ports:
      - "8554:8554"     # RTSP ingress/egress
    volumes:
      # Mount the configuration file into the container
      - ./rtsp-simple-server.yml:/app/rtsp-simple-server.yml
    command: ["/app/rtsp-simple-server", "/app/rtsp-simple-server.yml"] # Tell the server to use the config file

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
      - rtsp # Backend depends on the rtsp service
    environment:
      # Change VIDEO_SOURCE to point to the new stream path defined in the RTSP config
      # - VIDEO_SOURCE=rtsp://rtsp:8554/my_stream
      - VIDEO_SOURCE=/app/videos/test_video.mov
      - DATABASE_URL=postgresql://parking_user:parking_pass@db:5432/parking
      - FIREBASE_CRED=/secrets/firebase-sa.json
    volumes:
      - ./backend:/app
      - ./secrets/firebase-sa.json:/secrets/firebase-sa.json:ro
      - ./static:/static:ro
    ports:
      - "8000:8000"

volumes:
  pgdata:
