services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: parking_user
      POSTGRES_PASSWORD: parking_pass
      POSTGRES_DB: parking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rtsp:
    image: aler9/rtsp-simple-server
    ports:
      - "8554:8554"     # RTSP ingress/egress
    # You might need to add network_mode: host if running on Linux
    # or specific network configurations for Windows/macOS if default bridging isn't sufficient
    # For Windows, typically default bridge network works if ffmpeg pushes to localhost:8554

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
      # The backend depends on the rtsp service being available on the Docker network
      - rtsp
    environment:
      # Change VIDEO_SOURCE back to the RTSP stream from the rtsp service
      - VIDEO_SOURCE=rtsp://rtsp:8554/stream
      - DATABASE_URL=postgresql://parking_user:parking_pass@db:5432/parking
      - FIREBASE_CRED=/secrets/firebase-sa.json
    volumes:
      - ./backend:/app
      - ./secrets/firebase-sa.json:/secrets/firebase-sa.json:ro
      - ./static:/static:ro
      # Remove the videos volume mount as we are not using a local video file
      # - ./videos:/app/videos:ro
    ports:
      - "8000:8000"

volumes:
  pgdata: