"""Create occupancy table

Revision ID: 82b4c64b470e
Revises: 
Create Date: 2025-04-30 18:40:58.671508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b4c64b470e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupancy_camera_id'), 'occupancy', ['camera_id'], unique=False)
    op.create_index(op.f('ix_occupancy_timestamp'), 'occupancy', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occupancy_timestamp'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_camera_id'), table_name='occupancy')
    op.drop_table('occupancy')
    # ### end Alembic commands ###
