# File: .github/workflows/backend-deploy.yml
name: Deploy Backend to ECR and App Runner

on:
  push:
    branches:
      - main # Or your primary deployment branch
    paths:
      - 'backend/**' # Only run if changes are in the backend directory
      - '.github/workflows/backend-deploy.yml' # Or on changes to this workflow file itself
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required to use OIDC for AWS authentication
      contents: read  # Required to checkout the code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install/Update AWS CLI to latest v2 and Verify
        id: install_aws_cli
        run: |
          echo "Current AWS CLI version (before update attempt):"
          aws --version || echo "AWS CLI v1 not found or 'aws' command not in PATH yet."
          echo "Removing existing AWS CLI v1 if present..."
          sudo apt-get remove awscli -y --allow-remove-essential || true 
          echo "Installing/Updating AWS CLI v2..."
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          rm -rf awscliv2.zip aws/
          echo "Verifying AWS CLI installation..."
          echo "AWS CLI Path: $(which aws)"
          echo "Updated AWS CLI Version:"
          aws --version
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create secrets directory for Firebase credentials
        run: mkdir -p backend/secrets

      - name: Create firebase-sa.json from secret
        run: echo '${{ secrets.FIREBASE_SA_JSON_CONTENT }}' > backend/secrets/firebase-sa.json
        env:
          FIREBASE_SA_JSON_CONTENT: ${{ secrets.FIREBASE_SA_JSON_CONTENT }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_BACKEND }}
          IMAGE_TAG: ${{ github.sha }} # Use the commit SHA for a unique tag
        run: |
          echo "Building Docker image from context: ./backend"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f backend/Dockerfile ./backend
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image_uri=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update App Runner Service to use new image
        if: success() # Only run if previous steps succeeded
        env:
          APP_RUNNER_SERVICE_ARN: ${{ secrets.APP_RUNNER_SERVICE_ARN }}
          IMAGE_URI: ${{ steps.build-image.outputs.image_uri }}
        run: |
          echo "Using AWS CLI at: $(which aws)"
          aws --version
          echo "Updating App Runner service: $APP_RUNNER_SERVICE_ARN to use image $IMAGE_URI"
          
          CONFIG_FILE_PATH="${{ github.workspace }}/source-configuration-for-update.json"
          
          # JSON for update-service's --source-configuration
          # This structure is specific to the SourceConfiguration parameter of update-service
          jq -c -n \
            --arg image_identifier "$IMAGE_URI" \
            '{
              "ImageRepository": {
                "ImageIdentifier": $image_identifier,
                "ImageRepositoryType": "ECR",
                "ImageConfiguration": { "Port": "8000" }
              }
              # AutoDeploymentsEnabled is a separate top-level parameter for update-service, 
              # not part of this SourceConfiguration block if you were to set it.
              # For this image update, we only need to provide the ImageRepository details.
            }' > "$CONFIG_FILE_PATH"
          
          echo "Using Source Configuration for update-service from file: $CONFIG_FILE_PATH"
          echo "File content:"
          cat "$CONFIG_FILE_PATH"
          echo "--- End of file content ---"

          aws apprunner update-service \
            --service-arn "$APP_RUNNER_SERVICE_ARN" \
            --source-configuration "file://$CONFIG_FILE_PATH"
            
          echo "App Runner service update initiated. This should trigger a new deployment."
          # The update-service command itself usually triggers the deployment.
          # If you find it doesn't reliably, you might add a 'start-deployment' call after a short delay,
          # but it's often not needed.
          # Example:
          # sleep 10 # Wait a bit for the update to register
          # aws apprunner start-deployment --service-arn "$APP_RUNNER_SERVICE_ARN"
